name: 'Composition Repo - Build Release'

on:
  workflow_call:
    inputs:
      composition:
        description: "Composition repository, e.g. ose_composition_sjas"
        type: string
        required: true
      source_ref:
        description: "Git ref of next version, e.g. production"
        type: string
        required: true
      project:
        description: "Name of the project, e.g. sjas"
        type: string
        required: true
      # version:
      #   description: "Version to be deployed, e.g. 1.30.5 or 1.30.5-{SHA}"
      #   type: string
      #   required: true

    secrets:
      PUZZLE_REGISTRY:
        description: 'FQDN of the registry'
        required: true
      PUZZLE_REGISTRY_USERNAME:
        description: 'Username for the registry-robot-account'
        required: true
      PUZZLE_REGISTRY_PASSWORD:
        description: 'Password for the registry-robot-account'
        required: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout composition repo'
        uses: actions/checkout@v3
        with:
          repository: "hitobito/${{ inputs.composition }}"
          ref: ${{ inputs.source_ref }}
          submodules: true
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PUZZLE_REGISTRY }}
          username: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
          password: ${{ secrets.PUZZLE_REGISTRY_PASSWORD }}

      - uses: docker/build-push-action@v4
        with:
          file: hitobito/Dockerfile
          build-args: |
            BUILD_REPO=$GITHUB_REPOSITORY
            BUILD_REF=$GITHUB_REF_NAME
            BUILD_COMMIT=$GITHUB_SHA
          target: app
          tags: |
            ${{ secrets.PUZZLE_REGISTRY }}/hitobito/${{ inputs.project }}/rails:latest
          # ${{ secrets.PUZZLE_REGISTRY }}/hitobito/${{ inputs.project }}/rails:${{ inputs.version }}
          push: true
          no-cache: true

      - uses: docker/build-push-action@v4
        with:
          file: hitobito/Dockerfile
          build-args: |
            BUILD_REPO=$GITHUB_REPOSITORY
            BUILD_REF=$GITHUB_REF_NAME
            BUILD_COMMIT=$GITHUB_SHA
          target: sphinx
          tags: |
            ${{ secrets.PUZZLE_REGISTRY }}/hitobito/${{ inputs.project }}/sphinx:latest
          # ${{ secrets.PUZZLE_REGISTRY }}/hitobito/${{ inputs.project }}/sphinx:${{ inputs.version }}
          push: true
          no-cache: true
