name: "Notify statuscope of the Job-Result"

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository that the action is being run in"
        type: string
        required: true
      test_result:
        description: "Result of the Test-Run to report to statuscope"
        type: boolean
        required: true
    secrets:
      HEARTBEAT_URL:
        required: true
      HEARTBEAT_TOKEN:
        required: true
      HEARTBEAT_TEST:
        required: true

jobs:
  notify-statuscope:
    runs-on: 'ubuntu-latest'
    env:
      HEARTBEAT_URL: ${{ secrets.HEARTBEAT_URL }}
      HEARTBEAT_TEST: ${{ secrets.HEARTBEAT_TEST }}
      HEARTBEAT_TOKEN: ${{ secrets.HEARTBEAT_TOKEN }}
      HEARTBEAT_APPLICATION: "${{ inputs.repository }}-tests"

    steps:
      - name: 'Check Configuration'
        run: |
          echo "HEARTBEAT_APPLICATION is $HEARTBEAT_APPLICATION"

          (
          [[ "$HEARTBEAT_URL" != '' ]] &&
          [[ "$HEARTBEAT_TOKEN" != '' ]] &&
          echo "HEARTBEAT_URL and HEARTBEAT_TOKEN are present."
          ) || (
          echo "Please ensure that you have HEARTBEAT_URL and HEARTBEAT_TOKEN set as secrets"
          exit 1
          )

          echo "$HEARTBEAT_TEST"
          echo "${{ secrets.HEARTBEAT_TEST }}"

      - name: 'Send success'
        if: ${{ inputs.test_result == true }}
        run: >
          curl -v $HEARTBEAT_URL/signal \
            -d application=$HEARTBEAT_APPLICATION \
            -d token=$HEARTBEAT_TOKEN \
            -d status=ok | jq .

      - name: 'Send failure'
        if: ${{ inputs.test_result == false }}
        run: >
          curl -v $HEARTBEAT_URL/signal \
            -d application=$HEARTBEAT_APPLICATION \
            -d token=$HEARTBEAT_TOKEN \
            -d status=fail | jq .

