name: 'Composition Repo - Prepare Release'

on:
  workflow_call:
    inputs:
      composition:
        description: "Composition repository, e.g. ose_composition_pbs"
        type: string
        required: true
      wagon:
        description: "Name of the primary wagon"
        type: string
        required: true
      next_version:
        description: "Type of next version, generated or manual"
        required: true
        type: string
      version_string:
        description: "Version to be used"
        required: false
        type: string

permissions:
  contents: write

jobs:
  determine_version:
    runs-on: 'ubuntu-latest'
    outputs:
      version: ${{ steps.determine.outputs.version }}

    steps:
      - name: 'Checkout hitobito'
        uses: actions/checkout@v3
        with:
          repository: 'hitobito/hitobito'
          ref: feature/1975-prepare-release

      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1

      - name: 'Install dependencies'
        run: |
          gem install cmdparse

      - name: 'Get tag-names from repo'
        run: |
          git fetch --tags

      - name: 'Determine next version'
        id: determine
        env:
          VERSION_TYPE: ${{ inputs.next_version }}
        run: |
          next_version=$(bin/release suggest-version "$VERSION_TYPE")
          echo "version=test-${next_version}" >> "$GITHUB_OUTPUT"

  prepare_release:
    runs-on: 'ubuntu-latest'
    needs: determine_version

    steps:
      - name: 'Checkout composition repo'
        uses: actions/checkout@v3
        with:
          repository: "hitobito/${{ inputs.composition }}"
          submodules: true
          fetch-depth: 0

      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: hitobito

      - name: 'Install additional dependencies'
        run: |
          gem install cmdparse pastel

      - name: 'prepare submodule to the work-in-progress state'
        run: |
          cd hitobito && git fetch origin && git checkout -t origin/feature/1975-prepare-release

      - name: 'Prepare release'
        env:
          NEXT_VERSION: ${{ needs.determine_version.outputs.version }}
          FIRST_WAGON: ${{ inputs.wagon }}
        run: |
          echo "Preparing $NEXT_VERSION for $FIRST_WAGON"
          hitobito/bin/release composition "$FIRST_WAGON" "$NEXT_VERSION"
